services:
  - type: web
    name: s-saturno-affiliates-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: s-saturno-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: CORS_ORIGIN
        value: https://s-sat.onrender.com

databases:
  - name: s-saturno-db
    plan: free
    databaseName: ssaturno
    user: ssaturno